
CREATE FUNCTION ml_version()
RETURNS text
AS 'MODULE_PATHNAME','ml_version'
LANGUAGE C STRICT PARALLEL RESTRICTED;


CREATE FUNCTION ml_predict(
    model text,
    TABLENAME text
) RETURNS text
AS 'MODULE_PATHNAME','ml_predict'
LANGUAGE C STRICT PARALLEL RESTRICTED;

CREATE FUNCTION ml_info(model text )
RETURNS text
AS 'MODULE_PATHNAME','ml_info'
LANGUAGE C STRICT PARALLEL RESTRICTED;
